name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format-18
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-18

      - name: Check C++ formatting
        run: ./scripts/format.sh --check

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang-18 \
            cmake \
            ninja-build \
            mosquitto \
            mosquitto-clients \
            libprotobuf-dev \
            protobuf-compiler \
            libabsl-dev \
            libpaho-mqtt-dev

      - name: Start Mosquitto broker
        run: |
          sudo systemctl start mosquitto
          sudo systemctl status mosquitto
          # Wait a moment for broker to be ready
          sleep 2
          # Verify broker is accessible
          mosquitto_sub -h localhost -t test -C 1 -W 1 || true

      - name: Configure CMake
        env:
          CC: clang-18
          CXX: clang++-18
        run: cmake --preset default

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --preset default
